/* Build indicator: compile-time timestamp and configure-time flags.
 * BUILD_INFO.h is generated by CMake in the build directory. */

#include "build_info.h"

const char *BuildInfo = "Build " __DATE__ " " __TIME__ " (" BUILD_FLAGS_STR ")";
